# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'v_$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      displayName: 'Maven pom.xml'
      inputs:
        mavenPomFile: '$(Parameters.mavenPOMFile)'
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: 'kuberenetes-demo-manifests-master/kuberenetes-demo-manifests-master'
        Contents: 'backend-deployment.yaml'
        TargetFolder: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
    - task: Docker@2
      displayName: buildAndPush
      inputs:
        containerRegistry: 'kavya-docker-registry'
        repository: 'kavyareddy0911/demo-project-Maven-CI'
        Dockerfile: Dockerfile
        tags: 'v_$(Build.BuildId)'