pool:
  name: Azure Pipelines
  demands: maven

#Your build pipeline references an undefined variable named ‘Parameters.mavenPOMFile’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: '$(Parameters.mavenPOMFile)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: 'kuberenetes-demo-manifests-master/kuberenetes-demo-manifests-master'
    Contents: 'backend-deployment.yaml'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: Docker@2
  inputs:
    command: 'login'
    containerRegistry: mydockerconnection
- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: mydockerconnection
    repository: 'kavyareddy0911/demo-project-Maven-CI'
    Dockerfile: Dockerfile
    tags: 'v_$(Build.BuildId)'
